---
- name: WaddleBot
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  become: true
  become_user: root
  remote_user: root
  tasks:
    - name: Build
      loop_control:
        loop_var: job
      tags:
        - build
      include_tasks:
        file: "jobs/build/{{ job }}.yml"
        apply:
          tags: build
      loop:
        - filesystem
        - matterbridge
    - name: Run and Configure
      loop_control:
        loop_var: job
      tags:
        - run
        - configure
      include_tasks:
        file: "jobs/run/{{ job }}.yml"
        apply:
          tags: run
      loop:
        - run
