---
- name: Run the WaddleBot-Configurator configure script
  ansible.builtin.script: "/opt/manager/modules/WaddleBot-Configurator/app/configurator.py"
  args:
    executable: python3

- name: Debug the output of the WaddleBot-Configurator configure script
  debug:
    var: configurator

- name: Copy the newly created matterbridge.toml to the /opt/etc directory
  become: false
  ansible.builtin.copy:
    src: "/opt/manager/modules/WaddleBot-Configurator/app/matterbridge.toml"
    dest: "/etc/matterbridge/matterbridge.toml"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
